### ISSUE TITLE
[BUG] Pasting an image (created with the snipping tool in windows) caused a 500

### ISSUE THREAD

**Issue by dkorecko** [RARgames/4gaBoards#605]
**Describe the bug**

Whenever I take a screenshot in Windows with the snipping tool and I try pasting it into the board with a task open, it gets an infinite loading and gets a 500.

**Tech details**
 - 4ga Boards Version (Check in Settings/About): 3.2.6
 - Browser: Chrome
 - OS: Windows 11
 - Installation type (e.g. Docker/K8S/Manual): Docker (compose)

**Steps to reproduce** _(optional)_

**Expected behavior** _(optional)_

**Screenshots** _(optional)_

![Image](https://github.com/user-attachments/assets/8719985b-c2e1-445a-957f-aa4a932e0fe9)
![Image](https://github.com/user-attachments/assets/1bd5a612-c173-4a27-8909-07098c519084)

**Comment by RARgames** [comment]
Cannot reproduce on Chrome (win 10)

Could you check if you have the same issue on the demo instance: https://demo.4gaboards.com ?

**Comment by dkorecko** [comment]
The issue does not occur on the demo. Just tried on my local instance and the issue is still present, even on 3.2.7.

**Comment by RARgames** [comment]
This means that the problem is related just to your instance.

Could you check if there are any logs when you try to upload the file in the console? To check it, start 4ga Boards without detaching: `docker compose up`

**Comment by dkorecko** [comment]
```
2025-05-22 12:26:18 [E] Sending 500 ("Server Error") response: 
 EACCES: permission denied, mkdir '/app/private/attachments/0723c8ca-b95c-4f1a-9a40-dff1cc021026
```

I'm getting permission denied, just slightly confused since it should be running as root and db-data has no issue for example.

**Comment by dkorecko** [comment]
This is my compose:

```                                                                                        
services:
  db:
    container_name: 4ga-boards-db
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - boards-network
    volumes:
      - /media/toshi/4ga-data/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 4gaBoards
      POSTGRES_PASSWORD: redacted
      POSTGRES_INITDB_ARGS: "-A scram-sha-256"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d 4gaBoards"]
      interval: 1s
      timeout: 5s
      retries: 50
    labels:
      - wud.watch=false

  4gaBoards:
    container_name: 4ga-boards
    image: ghcr.io/rargames/4gaboards:3.2.7
    restart: unless-stopped
    networks:
      - boards-network
    volumes:
      - /media/toshi/4ga-data/user-avatars:/app/public/user-avatars
      - /media/toshi/4ga-data/project-background-images:/app/public/project-background-images
      - /media/toshi/4ga-data/attachments:/app/private/attachments
    ports:
      - 3566:1337
    environment:
      BASE_URL: http://trixx:3566
      SECRET_KEY: redacted
      DATABASE_URL: postgresql://postgres:redacted@db/4gaBoards
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    labels:
      - wud.tag.include=^\d+\.\d+\.\d+$$
networks:
  boards-network:
```
